version: '3'
services:
  mysql-dev:
    image: mysql:8.0.31-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_password
      - MYSQL_DATABASE=devcode-challenge
      - MYSQL_USER=triska
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
  mysql-test:
    image: mysql:8.0.31-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_password
      - MYSQL_DATABASE=devcode-challenge
      - MYSQL_USER=triska
      - MYSQL_PASSWORD=password
    ports:
      - 3307:3306